/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Story = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
});

export const idlService = IDL.Service({
  'addStory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getStory' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  
  return IDL.Service({
    'addStory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getStory' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };